name: Deploy Pages
permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      # Vite项目打包逻辑，已取消注释启用
      - name: 安装Node环境
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run build

      - name: 配置Pages
        uses: actions/configure-pages@v5
      - name: 上传静态产物
        uses: actions/upload-pages-artifact@v3
        with:
          # Vite打包输出目录dist
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: 部署站点
        id: deployment
        uses: actions/deploy-pages@v4
